# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Language Crash Courses
email: contact@languagecrashcourses.com
description:
  en: Learn the basics of a language fast and for free! Language Crash Courses presents a unique 5-step learning method that is based on simply reading, listening and repeating as a native speaker reads a story.  It’s the perfect way to get a taste of a language before going on a holiday or business trip. No need to struggle with grammar. Just enjoy and learn as you go. It's natural, intuitive, and best of all - it's fun!
  nl: I need a text and translation :( 
  es: yo también   

baseurl: "" # the subpath of your site, e.g. /blog..... use this if you want to run on github pages (/languagecrashcourses) and remove url below
url: "http://languagecrashcourses.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
facebook_username: languagecrashcourses

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  

defaults:
 -  scope: 
        path: ""
        type: "post"
    values:
          layout: "post"


 # Specify the name of a file to show as a masthead graphic at the top of each page, instead of the title, here:         
masthead: assets/img/logo/lcc-logo-2.svg

permalink: pretty

google_analytics: UA-165603066-1

t:
  en:
    home:
      name: "Home"
      url: "/"  
    about:
      name: "About"
      url: "/about/"
    contact:
      name: "Contact"
      url: "/contact/"
    donate:
      name: "Donate"
      url: "/donate/"
    get-involved:
      name: "Get involved"
      url: "/get-involved/"
    variables: 
      sitelanguage: "Site Language"
      language: "English"
      img: assets/img/flags/united-kingdom-flag-icon.png
  nl:
    home:
      name: "NlHome"
      url: "/dir/dutch/home"
    about:
      name: "Over"
      url: "/dir/dutch/about"
    contact:
      name: "Contact"
      url: "/dir/dutch/contact"
    donate:
      name: "Doneren"
      url: "/dir/dutch/donate"
    get-involved:
      name: "Eaak betrokken"
      url: "/dir/dutch/get-involved"
    variables: 
      sitelanguage: "&nbsp; &nbsp; &nbsp; Site Taal &nbsp;"
      language: "Nederlands"
      img: assets/img/flags/netherlands-flag-icon.png
  es:
    home:
      name: "EsHome"
      url: "/dir/spanish/home"
    about:
      name: "Over"
      url: "/dir/dutch/about"
    contact:
      name: "Contact"
      url: "/dir/dutch/contact"
    donate:
      name: "Doneren"
      url: "/dir/dutch/donate"
    get-involved:
      name: "Eaak betrokken"
      url: "/dir/dutch/get-involved"
    variables: 
      sitelanguage: "Lenguaje Del Sitio"
      language: "Español"
      img: assets/img/flags/spain-flag-icon.png


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
